

[lacros_dacapo]
    location = "Punta Arenas"
    coordinates = [-53.1354, -70.8845]
    altitude = 9
    duration = [["20181127", "today"]]
    systems = ["MIRA", "CLOUDNET", "CLOUDNET_LIMRAD", "LIMRAD94", "PARSIVEL",
               "MRRPRO", "SHAUN", "POLLY", "POLLYNET", "POLLYNETprofiles", "peakTree", "HATPRO"]
    mira_azi_zero = 138
    cloudnet_stationname = 'punta-arenas'
    param_config_file = 'params_dacapo.toml'
    connectordump = '/home/larda3/larda-connectordump'

[lacros_cycare]
    location = "Limassol"
    coordinates = [34.677, 33.038]
    altitude = 11
    mira_azi_zero = 154
    duration = [["20161018", "20180325"]]
    systems = ["MIRA", "CLOUDNET", "PARSIVEL", "peakTree", 
               "MRRPRO", "SHAUN", "POLLY", "POLLYNET", "POLLYNETprofiles", "POLLYraw"]
    cloudnet_stationname = 'limassol'
    param_config_file = 'params_cycare.toml'
    connectordump = '/home/larda3/larda-connectordump/'

[lacros_accept]
    location = "Cabauw"
    coordinates = [51.97, 4.927]
    altitude = 0
    mira_azi_zero = 0
    duration = [["20141001", "20141120"]]
    systems = ["MIRA", "CLOUDNET", 
               "SHAUN", "POLLY"]
    cloudnet_stationname = 'cesar'
    param_config_file = 'params_accept.toml'
    connectordump = '/home/larda3/larda-connectordump/'

[oceanet_pascal]
    location = "Polarstern"
    coordinates = [90, 0]
    altitude = 10
    mira_azi_zero = 0
    duration = [["20170524", "20170718"]]
    systems = ["MIRA", "CLOUDNET", 
               "POLLY"]
    cloudnet_stationname = 'polarstern'
    param_config_file = 'params_pascal.toml'
    connectordump = '/home/larda3/larda-connectordump/'

[colrawi]
    location = "Lindenberg"
    coordinates = [52.209619, 14.128879]
    altitude = 104
    mira_azi_zero = 0
    duration = [["20150530", "20150901"]]
    systems = ["MIRA", "CLOUDNET", 
               "SHAUN", "POLLY", "MOLE"]
    cloudnet_stationname = 'lindenberg'
    param_config_file = 'params_colrawi.toml'
    connectordump = '/home/larda3/larda-connectordump/'

[lacros_leipzig]
    location = "Leipzig"
    coordinates = [51.353399, 12.434687]
    altitude = 123
    mira_azi_zero = 0
    duration = [["20150608", "20160923"], ["20180428", "20180904"]]
    systems = ["MIRA", "CLOUDNET", 
               "SHAUN", "POLLY", "PARSIVEL"]
    cloudnet_stationname = 'leipzig'
    param_config_file = 'params_lacros_leipzig.toml'
    connectordump = '/home/larda3/larda-connectordump/'

[arm_baecc]
    location = "Hyyti채l채"
    coordinates = [61.84, 24.28]
    altitude = 174
    mira_azi_zero = 0
    duration = [["20140201", "20140913"]]
    systems = ["peakTree", "KAZR"]
    cloudnet_stationname = "hyyti채l채"
    param_config_file = "params_baecc.toml"
    connectordump = '/home/larda3/larda-connectordump/'

[davos]
    location = "Davos"
    coordinates = [-53.1354, -70.8845]
    altitude = 1627
    duration = [["20190210", "20190322"]]
    systems = ["MIRA", "CLOUDNET", 
               #"SHAUN","peakTree", "PARSIVEL",
               "POLLY", "POLLYNET", "POLLYNETprofiles", "POLLYraw"]
    mira_azi_zero = 0 
    cloudnet_stationname = 'davos'
    param_config_file = 'params_davos.toml'
    connectordump = '/home/larda3/larda-connectordump/'


[test_filepatterns]
    location = "Punta Arenas"
    coordinates = [-53.1354, -70.8845]
    altitude = 9
    mira_azi_zero = 0
    duration = [["20181127", "today"]]
    #systems = ["MIRA", "CLOUDNET", "CLOUDNET_LIMRAD", "LIMRAD94",
    #           "MRRPRO", "SHAUN", "POLLY"]
    systems = ["CLOUDNET_LIMRAD"]
    cloudnet_stationname = 'punta-arenas'
    #param_config_file = 'test_filepatterns.toml'
    #param_config_file = 'test_filepatterns_cloudnet.toml'
    param_config_file = 'test_filepatterns_cloudnet_limrad.toml'
    connectordump = '/home/larda3/larda-connectordump/'
