

[LIMRAD94]
  [LIMRAD94.path.l1]
    base_dir = '/lacroshome/remsens_lim/data/limrad94/'
    matching_subdirs = '(Y\d{4}\/M\d{2}\/D\d{2}.*\d{6}_\d{6}.*.LV1.NC)'
    date_in_filename = '(?P<year>\d{2})(?P<month>\d{2})(?P<day>\d{2})_(?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2})'
  [LIMRAD94.path.l0]
    #base_dir = '/raid6_90TB/instruments/limrad94/'
    base_dir = '/lacroshome/remsens_lim/data/limrad94/'
    matching_subdirs = '(Y\d{4}\/M\d{2}\/D\d{2}.*\d{6}_\d{6}.*.LV0.NC)'
    date_in_filename = '(?P<year>\d{2})(?P<month>\d{2})(?P<day>\d{2})_(?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2})'
  [LIMRAD94.generic]
    # this general settings need to be handed down to the params
    colormap = "gist_rainbow"
    which_path = 'l1'
    time_variable = 'Time'
    chirp_variable = 'Chirp'
    time_millisec_variable = 'Timems'
    time_conversion = 'since20010101'
    range_conversion = 'none'
    var_conversion = 'none'
    # currently a special reader is needed just for limrad
    # this one stacks the chirps and loads the range form lvl0
    ncreader = 'timeheight_limrad94'
    # if identifier is given read from ncfile, else define here
    rg_unit = 'm'
    identifier_var_unit = 'Units'
    fill_value = -999.0
  [LIMRAD94.params.Ze]
    variable_name = 'ZE'
    var_lims = [ -40, 20 ]
  [LIMRAD94.params.VEL]
    variable_name = 'MeanVel'
    colormap = 'carbonne'
    var_lims = [-6, 6]
