[bco]
    location = "Barbados"
    coordinates = [-53.1354, -70.8845]
    altitude = 9
    duration = [["20110101", "today"]]
    #systems = ["CLOUDNET", "WBAND", "KATRIN", "MMCR__MBR2", "BCO_CHM15k_10s", "BCO_CHM15k_30S"]
    systems = ["KATRIN"]
    mira_azi_zero = 138
    cloudnet_stationname = 'bco'
    param_config_file = 'bco_cloudnet.toml'
    connectordump = '/Users/willi/code/python/larda3/larda-connectordump'

[leipzig_gpu]
    location = "Leipzig, LIM"
    coordinates = [51.333687, 12.388384]
    altitude = 117
    duration = [["20200101", "today"]]
    systems = ["LIMRAD94",  "HATPRO", "LIMCUBE"]
    mira_azi_zero = -999
    cloudnet_stationname = 'none'
    param_config_file = 'params_leipzig_gpu.toml'
    connectordump = '/home/sdig/code/larda3/larda-connectordump'

[leipzig_rs01]
    location = "Leipzig, LIM"
    coordinates = [51.333687, 12.388384]
    altitude = 117
    duration = [["20100101", "today"]]
    systems = ["LIMRAD94",  "HATPRO", "LIMCUBE"]
    mira_azi_zero = -999
    cloudnet_stationname = 'none'
    param_config_file = 'params_leipzig_rs01.toml'
    connectordump = '/home/remsens01/code/larda3/larda-connectordump'

[eurec4a]
    location = "RV-Meteor"
    coordinates = [13.0, -57.7]
    altitude = 16
    duration = [["20200114", "20200229"]]
    systems = ["LIMRAD94",  "HATPRO", "CEILO", "LIMRAD94_cn_input", "LIMRAD94_cni", "LIMRAD94_cni_hc", "LIMRAD94_cni_hc_dea", "LIMRAD94_30s", "LIMRAD94_tmp"]
    mira_azi_zero = -999
    cloudnet_stationname = 'none'
    param_config_file = 'params_eurec4a.toml'
    connectordump = '/projekt1/remsens/work/jroettenbacher/Base/larda-connectordump'

[lacros_dacapo_catalpa]
    location = "Punta Arenas"
    coordinates = [-53.1354, -70.8845]
    altitude = 9
    duration = [["20181127", "today"]]
    systems = ["LIMRAD94",  "HATPRO"]
    mira_azi_zero = 138
    cloudnet_stationname = 'punta-arenas'
    param_config_file = 'params_dacapo_catalpa.toml'
    connectordump = '/projekt1/remsens/work/jroettenbacher/Base/larda-connectordump'

[lacros_dacapo_gpu]
    location = "Punta Arenas"
    coordinates = [-53.1354, -70.8845]
    altitude = 9
    duration = [["20181127", "today"]]
    systems = ["MIRA", "CLOUDNET", "CLOUDNET_LIMRAD", "CLOUDNETpy35", "CLOUDNETpy94", "LIMRAD94", "PARSIVEL",
               "MRRPRO", "SHAUN", "POLLY", "POLLYNET", "POLLYNETprofiles", "peakTree", "HATPRO", "LIMRAD94_cn_input"]
    mira_azi_zero = 138
    cloudnet_stationname = 'punta-arenas'
    param_config_file = 'params_dacapo_gpu.toml'
    connectordump = '/home/sdig/code/larda3/larda-connectordump'

[lindenberg_mol]
    location = "Lindenberg, MOL"
    coordinates = [52.209433, 14.128580]
    altitude = 104
    duration = [["20200714", "20201020"]]
    systems = ["LIMRAD94",  "HATPRO", "LIMCUBE", "MIRA", "HATPRO-DWD", "CEILO-DWD", "DL-DWD", "LIMRAD24"]
    mira_azi_zero = -999
    cloudnet_stationname = 'lindenberg'
    param_config_file = 'params_lindenberg.toml'
    connectordump = '/home/remsens01/code/larda3/larda-connectordump'



#[lacros_dacapo]
#    location = "Punta Arenas"
#    coordinates = [-53.1354, -70.8845]
#    altitude = 9
#    duration = [["20181127", "today"]]
#    systems = ["MIRA", "CLOUDNET", "CLOUDNET_LIMRAD", "LIMRAD94", "PARSIVEL",
#               "MRRPRO", "SHAUN", "POLLY", "POLLYNET", "peakTree", "HATPRO"]
#    mira_azi_zero = 138
#    cloudnet_stationname = 'punta-arenas'
#    param_config_file = 'params_dacapo.toml'
#    connectordump = '/home/larda3/larda-connectordump'
#
#[lacros_cycare]
#    location = "Limassol"
#    coordinates = [34.677, 33.038]
#    altitude = 11
#    duration = [["20161018", "20180325"]]
#    systems = ["MIRA", "CLOUDNET",
#               "MRRPRO", "SHAUN", "POLLY"]
#    mira_azi_zero = 138
#    cloudnet_stationname = 'limassol'
#    param_config_file = 'params_cycare.toml'
#    connectordump = '/home/larda3/larda-connectordump/'

[lacros_accept_gpu]
    location = "Cabauw"
    coordinates = [51.97, 4.927]
    altitude = 0
    mira_azi_zero = 0
    duration = [["20141001", "20141120"]]
    systems = ["MIRA", "CLOUDNET", "SHAUN", "POLLY"]
    cloudnet_stationname = 'cesar'
    param_config_file = 'params_accept_gpu.toml'
    connectordump = '/home/sdig/code/larda3/larda-connectordump'

#[test_filepatterns]
#    location = "Punta Arenas"
#    coordinates = [-53.1354, -70.8845]
#    altitude = 9
#    duration = [["20181127", "today"]]
#    #systems = ["MIRA", "CLOUDNET", "CLOUDNET_LIMRAD", "LIMRAD94",
#    #           "MRRPRO", "SHAUN", "POLLY"]
#    systems = ["CLOUDNET_LIMRAD"]
#    cloudnet_stationname = 'punta-arenas'
#    #param_config_file = 'test_filepatterns.toml'
#    #param_config_file = 'test_filepatterns_cloudnet.toml'
#    param_config_file = 'test_filepatterns_cloudnet_limrad.toml'
#    connectordump = '/home/larda3/larda-connectordump/'
