
[LIMRAD94]
  [LIMRAD94.path.l1]
    base_dir = '/projekt2/remsens/data/campaigns/eurec4a/LIMRAD94/'
    matching_subdirs = '(Y\d{4}\/M\d{2}\/D\d{2}.*\d{6}_\d{6}.*.LV1.(?i)NC)'
    date_in_filename = '(?P<year>\d{2})(?P<month>\d{2})(?P<day>\d{2})_(?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2})'
  [LIMRAD94.path.l0]
    base_dir = '/projekt2/remsens/data/campaigns/eurec4a/LIMRAD94/'
    matching_subdirs = '(Y\d{4}\/M\d{2}\/D\d{2}.*\d{6}_\d{6}.*.LV0.(?i)NC)'
    date_in_filename = '(?P<year>\d{2})(?P<month>\d{2})(?P<day>\d{2})_(?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2})'
  [LIMRAD94.generic]
    # this general settings need to be handed down to the params
    colormap = "gist_rainbow"
    which_path = 'l1'
    time_variable = 'Time'
    chirp_variable = 'Chirp'
    time_millisec_variable = 'Timems'
    time_conversion = 'since20010101'
    range_conversion = 'none'
    var_conversion = 'none'
    # currently a special reader is needed just for limrad
    # this one stacks the chirps and loads the range form lvl0
    ncreader = 'timeheight_limrad94'
    # if identifier is given read from ncfile, else define here
    rg_unit = 'm'
    identifier_var_unit = 'Units'
    fill_value = -999.0
    description_file = 'limrad94_general.rst'
  [LIMRAD94.params.Ze]
    variable_name = 'ZE'
    var_unit = 'mm^6/m^3'
    colormap = 'jet'
    var_lims = [ -40, 20 ]
  [LIMRAD94.params.VEL]
    variable_name = 'MeanVel'
    colormap = 'jet'
    var_unit = 'm/s'
    var_lims = [-4, 3]
  [LIMRAD94.params.sw]
    variable_name = 'SpecWidth'
    colormap = 'jet'
    var_unit = 'm/s'
    var_lims = [0.01, 2.0]
  [LIMRAD94.params.skew]
    variable_name = 'Skew'
    colormap = 'jet'
    var_unit = ''
    var_lims = [-1, 1]
  [LIMRAD94.params.kurt]
    variable_name = 'Kurt'
    colormap = 'jet'
    var_unit = ''
    var_lims = [0, 3]
  [LIMRAD94.params.ZDR]
    variable_name = 'ZDR'
    colormap = 'jet'
    var_unit = 'dB'
    var_lims = [-0.5, 1.5]
  [LIMRAD94.params.RHV]
    variable_name = 'RHV'
    colormap = 'jet'
    var_unit = '1'
    var_lims = [0.8, 1.0]
  [LIMRAD94.params.SLv]
    variable_name = 'SLv'
    colormap = 'jet'
    var_lims = [-40, 20]
  [LIMRAD94.params.DiffAtt]
    variable_name = 'DiffAtt'
    colormap = 'jet'
    var_lims = []
  [LIMRAD94.params.PhiDP]
    variable_name = 'PhiDP'
    colormap = 'jet'
    var_unit = 'rad'
    var_lims = [0, 7]
  [LIMRAD94.params.ldr]
    variable_name = 'SLDR'
    colormap = 'LDR'
    var_lims = []
  [LIMRAD94.params.LWP]
    variable_name = 'LWP'
    ncreader = 'time'
    var_lims = [-100, 1000]
  [LIMRAD94.params.SurfTemp]
    variable_name = 'SurfTemp'
    ncreader = 'time'
    var_lims = [0, 400]
  [LIMRAD94.params.SurfPres]
    variable_name = 'SurfPres'
    ncreader = 'time'
    var_lims = [900, 1100]
  [LIMRAD94.params.SurfRelHum]
    variable_name = 'SurfRelHum'
    ncreader = 'time'
    var_lims = [0, 100]
  [LIMRAD94.params.SurfWS]
    variable_name = 'SurfWS'
    ncreader = 'time'
    var_lims = [0, 25]
  [LIMRAD94.params.SurfWD]
    variable_name = 'SurfWD'
    ncreader = 'time'
    var_lims = [0, 360]
  [LIMRAD94.params.bt]
    variable_name = 'DDTb'
    ncreader = 'time'
    var_lims = []
  [LIMRAD94.params.rr]
    variable_name = 'Rain'
    ncreader = 'time'
    var_lims = [0, 500]
  [LIMRAD94.params.MaxVel]
    variable_name = 'MaxVel'
    ncreader = 'aux'
    var_lims = []
  [LIMRAD94.params.AvgNum]
    variable_name = 'AvgNum'
    ncreader = 'aux'
    var_unit = '-'
    var_lims = []
  [LIMRAD94.params.DoppLen]
    variable_name = 'DoppLen'
    ncreader = 'aux'
    var_unit = '-'
    var_lims = []
  [LIMRAD94.params.RangeRes]
    variable_name = 'RangeRes'
    ncreader = 'aux'
    var_lims = []
  [LIMRAD94.params.ChirpFFTSize]
    which_path = 'l0'
    variable_name = 'ChirpFFTSize'
    ncreader = 'aux'
    var_lims = []
  [LIMRAD94.params.Inc_El]
    variable_name = 'Inc_El'
    ncreader = 'time'
    var_unit = 'deg'
    var_lims = [-45.0, 45.0]
  [LIMRAD94.params.Inc_ElA]
    variable_name = 'Inc_ElA'
    ncreader = 'time'
    var_unit = 'deg'
    var_lims = [-45.0, 45.0]
  [LIMRAD94.params.C1Range]
    which_path = 'l0'
    variable_name = 'C1Range'
    var_unit = 'm'
    ncreader = 'aux'
    var_lims = []
  [LIMRAD94.params.C2Range]
    which_path = 'l0'
    variable_name = 'C2Range'
    var_unit = 'm'
    ncreader = 'aux'
    var_lims = []
  [LIMRAD94.params.C3Range]
    which_path = 'l0'
    variable_name = 'C3Range'
    var_unit = 'm'
    ncreader = 'aux'
    var_lims = []
  [LIMRAD94.params.C1HSpec]
    which_path = 'l0'
    variable_name = 'C1HSpec'
    vel_ext_variable = ['MaxVel','0']
    range_variable = 'C1Range'
    ncreader = 'spec'
    var_unit = 'Z m-1 s'
    var_lims = [-50, 20]
    rg_unit = 'm'
    var_conversion = 'none'
  [LIMRAD94.params.C2HSpec]
    which_path = 'l0'
    variable_name = 'C2HSpec'
    vel_ext_variable = ['MaxVel','1']
    range_variable = 'C2Range'
    ncreader = 'spec'
    var_unit = 'Z m-1 s'
    var_lims = [-50, 20]
    rg_unit = 'm'
    var_conversion = 'none'
  [LIMRAD94.params.C3HSpec]
    which_path = 'l0'
    variable_name = 'C3HSpec'
    vel_ext_variable = ['MaxVel','2']
    range_variable = 'C3Range'
    ncreader = 'spec'
    var_unit = 'Z m-1 s'
    var_lims = [-50, 20]
    rg_unit = 'm'
    var_conversion = 'none'
  [LIMRAD94.params.C1VSpec]
    which_path = 'l0'
    variable_name = 'C1VSpec'
    vel_ext_variable = ['MaxVel','0']
    range_variable = 'C1Range'
    ncreader = 'spec'
    var_unit = 'Z m-1 s'
    var_lims = [-50, 20]
    rg_unit = 'm'
    var_conversion = 'none'
  [LIMRAD94.params.C2VSpec]
    which_path = 'l0'
    variable_name = 'C2VSpec'
    vel_ext_variable = ['MaxVel','1']
    range_variable = 'C2Range'
    ncreader = 'spec'
    var_unit = 'Z m-1 s'
    var_lims = [-50, 20]
    rg_unit = 'm'
    var_conversion = 'none'
  [LIMRAD94.params.C3VSpec]
    which_path = 'l0'
    variable_name = 'C3VSpec'
    vel_ext_variable = ['MaxVel','2']
    range_variable = 'C3Range'
    ncreader = 'spec'
    var_unit = 'Z m-1 s'
    var_lims = [-50, 20]
    rg_unit = 'm'
    var_conversion = 'none'
  [LIMRAD94.params.HSpec]
    which_path = 'l0'
    variable_name = 'HSpec'
    vel_ext_variable = ['MaxVel','0']
    range_variable = 'Range'
    ncreader = 'spec_limrad94'
    var_unit = 'Z m-1 s'
    var_lims = [-50, 20]
    rg_unit = 'm'
    var_conversion = 'divideby2'
  [LIMRAD94.params.VSpec]
    which_path = 'l0'
    variable_name = 'VSpec'
    vel_ext_variable = ['MaxVel','0']
    range_variable = 'Range'
    ncreader = 'spec_limrad94'
    var_unit = 'Z m-1 s'
    var_lims = [-50, 20]
    rg_unit = 'm'
    var_conversion = 'divideby2'
  [LIMRAD94.params.C1VNoisePow]
    which_path = 'l0'
    variable_name = 'C1VNoisePow'
    var_unit = 'm^6 m^-3'
    var_lims = [-50, 20]
    rg_unit = 'm'
  [LIMRAD94.params.C2VNoisePow]
    which_path = 'l0'
    variable_name = 'C2VNoisePow'
    var_unit = 'm^6 m^-3'
    var_lims = [-50, 20]
    rg_unit = 'm'
  [LIMRAD94.params.C3VNoisePow]
    which_path = 'l0'
    variable_name = 'C3VNoisePow'
    var_unit = 'm^6 m^-3'
    var_lims = [-50, 20]
    rg_unit = 'm'
  [LIMRAD94.params.VNoisePow]
    which_path = 'l0'
    variable_name = 'VNoisePow'
    var_unit = 'mm^6/m^3'
    colormap = 'jet'
    var_lims = [ -50, 20 ]
  [LIMRAD94.params.C1HNoisePow]
    which_path = 'l0'
    variable_name = 'C1HNoisePow'
    var_unit = 'm^6 m^-3'
    var_lims = [-50, 20]
    rg_unit = 'm'
  [LIMRAD94.params.C2HNoisePow]
    which_path = 'l0'
    variable_name = 'C2HNoisePow'
    var_unit = 'm^6 m^-3'
    var_lims = [-50, 20]
    rg_unit = 'm'
  [LIMRAD94.params.C3HNoisePow]
    which_path = 'l0'
    variable_name = 'C3HNoisePow'
    var_unit = 'm^6 m^-3'
    var_lims = [-50, 20]
    rg_unit = 'm'
  [LIMRAD94.params.HNoisePow]
    which_path = 'l0'
    variable_name = 'HNoisePow'
    var_unit = 'mm^6/m^3'
    colormap = 'jet'
    var_lims = [-50, 20]

[LIMRAD94_cn_input]
  [LIMRAD94_cn_input.path.nc]
    base_dir = '/projekt2/remsens/data/campaigns/eurec4a/LIMRAD94/cloudnet_input/'
    matching_subdirs = '(.*\d{8}_\d{6}-\d{6}_LIMRAD94.nc)'
    date_in_filename = '(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})'
    # _(?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2})
  [LIMRAD94_cn_input.generic]
    # this general settings need to be handed down to the params
    colormap = "gist_rainbow"
    which_path = 'nc'
    time_variable = 'time'
    range_variable = 'range'
    # time_millisec_variable = 'Timems'
    time_conversion = 'since20010101'
    #TODO: range conversion from sea level to Navi Deck
    range_conversion = 'none'
    var_conversion = 'none'
    ncreader = 'timeheight'
    # if identifier is given read from ncfile, else define here
    rg_unit = 'm'
    identifier_var_unit = 'Units'
    fill_value = -999.0
    description_file = 'limrad94_general.rst'
  [LIMRAD94_cn_input.params.Ze]
    variable_name = 'Ze'
    var_unit = 'mm^6/m^3'
    colormap = 'jet'
    var_lims = [ -40, 20 ]
  [LIMRAD94_cn_input.params.Vel]
    variable_name = 'vm'
    colormap = 'jet'
    var_unit = 'm/s'
    var_lims = [-4, 3]
  [LIMRAD94_cn_input.params.sw]
    variable_name = 'sigma'
    colormap = 'jet'
    var_unit = 'm/s'
    var_lims = [0.01, 2.0]
  [LIMRAD94_cn_input.params.ldr]
    variable_name = 'ldr'
    colormap = 'LDR'
    var_lims = []
  [LIMRAD94_cn_input.params.skew]
    variable_name = 'Skew'
    colormap = 'jet'
    var_unit = ''
    var_lims = [-1, 1]
  [LIMRAD94_cn_input.params.kurt]
    variable_name = 'kurt'
    colormap = 'jet'
    var_unit = ''
    var_lims = [0, 3]
  [LIMRAD94_cn_input.params.DiffAtt]
    variable_name = 'DiffAtt'
    colormap = 'jet'
    var_lims = []
  [LIMRAD94_cn_input.params.bt]
    variable_name = 'bt'
    ncreader = 'time'
    var_lims = []
  [LIMRAD94_cn_input.params.LWP]
    variable_name = 'lwp'
    ncreader = 'time'
    var_lims = [-100, 1000]
  [LIMRAD94_cn_input.params.rr]
    variable_name = 'rain'
    ncreader = 'time'
    var_lims = [0, 500]
  [LIMRAD94_cn_input.params.SurfRelHum]
    variable_name = 'SurfRelHum'
    ncreader = 'time'
    var_lims = [0, 100]
  [LIMRAD94_cn_input.params.Inc_ElA]
    variable_name = 'Inc_ElA'
    ncreader = 'time'
    var_unit = 'deg'
    var_lims = [-2.0, 2.0]
  [LIMRAD94_cn_input.params.Inc_El]
    variable_name = 'Inc_El'
    ncreader = 'time'
    var_unit = 'deg'
    var_lims = [-2.0, 2.0]
  [LIMRAD94_cn_input.params.MaxVel]
    variable_name = 'DoppMax'
    ncreader = 'aux'
    var_lims = []
[LIMRAD94_cn_input.params.range_offset]
    variable_name = 'range_offset'
    ncreader = 'aux'
    var_lims = []
[LIMRAD94_cn_input.params.cloud_bases_tops]
    variable_name = 'cloud_bases_tops'
    var_unit = ''
    colormap = 'PRGn'
    var_lims = [ -1, 1 ]

[LIMRAD94_30s]
  [LIMRAD94_30s.path.nc]
    base_dir = '/projekt2/remsens/data/campaigns/eurec4a/LIMRAD94/30s_averages/'
    matching_subdirs = '(.*RV-METEOR_LIMRAD94_Ze_\d{8}.nc)'
    date_in_filename = '(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})'
    # _(?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2})
  [LIMRAD94_30s.generic]
    # this general settings need to be handed down to the params
    colormap = "gist_rainbow"
    which_path = 'nc'
    time_variable = 'time'
    range_variable = 'range'
    # time_millisec_variable = 'Timems'
    time_conversion = 'since20010101'
    #TODO: range conversion from sea level to Navi Deck
    range_conversion = 'none'
    var_conversion = 'none'
    ncreader = 'timeheight'
    # if identifier is given read from ncfile, else define here
    rg_unit = 'm'
    identifier_var_unit = 'Units'
    fill_value = -999.0
    description_file = 'limrad94_general.rst'
  [LIMRAD94_30s.params.Ze]
    variable_name = 'Ze'
    var_unit = 'mm^6/m^3'
    colormap = 'jet'
    var_lims = [ -40, 20 ]
  [LIMRAD94_30s.params.cloud_bases_tops]
    variable_name = 'cloud_bases_tops'
    var_unit = ''
    colormap = 'PRGn'
    var_lims = [ -1, 1 ]

[HATPRO]
  [HATPRO.path.lv2_prw]
    # mastering regex (here to exclude ppi and stuff)
    base_dir = '/projekt2/remsens/data/HATPRO/rvm/data/level2/'
    matching_subdirs = '(\d{4}\/sups_met_mwr00_l2_prw_v00_\d{14}.nc)'
    date_in_filename = '(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})(?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2})'
  [HATPRO.path.lv2_hua]
    # mastering regex (here to exclude ppi and stuff)
    base_dir = '/projekt2/remsens/data/HATPRO/rvm/data/level2/'
    matching_subdirs = '(\d{4}\/sups_met_mwr00_l2_hua_v00_\d{14}.nc)'
    date_in_filename = '(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})(?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2})'
  [HATPRO.path.lv2_clwvi]
    # mastering regex (here to exclude ppi and stuff)
    base_dir = '/projekt2/remsens/data/HATPRO/rvm/data/level2/'
    matching_subdirs = '(\d{4}\/sups_met_mwr00_l2_clwvi_v00_\d{14}.nc)'
    date_in_filename = '(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})(?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2})'
  [HATPRO.path.lv2_ta]
    # mastering regex (here to exclude ppi and stuff)
    base_dir = '/projekt2/remsens/data/HATPRO/rvm/data/level2/'
    matching_subdirs = '(\d{4}\/sups_met_mwr00_l2_ta_v00_\d{14}.nc)'
    date_in_filename = '(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})(?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2})'
  # this general settings need to be handed down to the params
  [HATPRO.generic]
    time_variable = 'time'
    range_variable = 'height'
    colormap = "jet"
    which_path = 'nc'
    # define how the values from the nc file have to
    # be converted (strings defined in pyLARDA.helpers)
    #time_conversion = 'since19691231'
    time_conversion = 'unix'
    range_conversion = 'none'
    var_conversion = 'none'
    ncreader = 'timeheight'
    # if identifier is given read from ncfile, else define here
    identifier_rg_unit = 'units'
    identifier_var_unit = 'units'
    var_lims = [-40, 20]
  [HATPRO.params.LWP]
    which_path = 'lv2_clwvi'
    variable_name = 'clwvi'
    ncreader = 'time'
    var_lims = [-25, 500]
  [HATPRO.params.flag]
    which_path = 'lv2_clwvi'
    variable_name = 'flag'
    ncreader = 'time'
    #var_lims = [-25, 500]
  [HATPRO.params.ABSH]
    which_path = 'lv2_hua'
    variable_name = 'hua'
    var_lims = [0.0, 0.02]
  [HATPRO.params.T]
    which_path = 'lv2_ta'
    variable_name = 'ta'
    var_lims = [200, 320]
  [HATPRO.params.IWV]
    which_path = 'lv2_prw'
    variable_name = 'prw'
    ncreader = 'time'
    var_lims = [0, 50]

[CEILO]
  [CEILO.path.nc]
    # mastering regex (here to exclude ppi and stuff)
    base_dir = '/projekt2/remsens/data/campaigns/eurec4a/RV-METEOR_CEILOMETER/CHM170158/'
    matching_subdirs = '(\d{4}\/\d{2}\/\d{8}_FSMETEOR_CHM170158.nc)'
    date_in_filename = '(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})'
  # this general settings need to be handed down to the params
  [CEILO.generic]
    time_variable = 'time'
    range_variable = 'layer'
    colormap = "gist_rainbow"
    which_path = 'nc'
    # define how the values from the nc file have to
    # be converted (strings defined in pyLARDA.helpers)
    time_conversion = 'since19040101'
    range_conversion = 'none'
    var_conversion = 'none'
    ncreader = 'time'
    # if identifier is given read from ncfile, else define here
    identifier_rg_unit = 'units'
    identifier_var_unit = 'units'
    identifier_var_lims = 'plot_range'
    # identifier_fill_value = 'missing_value'
  [CEILO.params.beta]
    variable_name = 'beta_raw'
    var_unit = ''
    var_lims = [-6e7,2e8]
    rg_unit = 'm'
   # Punta Arenas variables:
   # [CEILO.params.beta]
   # variable_name = 'beta'
   # var_unit = 'sr^-1^ m^-2'
   # var_lims = [0, 1e-2]
   # rg_unit = 'm'
  [CEILO.params.cbh]
    variable_name = 'cbh'
    var_unit = 'm'
    var_lims = [0, 15000]
    rg_unit = 'm'
   # Punta Arenas variables:
   # variable_name = 'att_beta_1064'
   # var_unit = 'm'
   # var_lims = [0, 1e-2]
   # rg_unit = 'm'
