 

[MIRA]
  [MIRA.path.mmclx]
    # mastering regex (here to exclude ppi and stuff)
    base_dir = '/lacroshome/mira/data/polarstern/'
    #matching_subdirs = 'mom\/\d{4}\.*\/\d{8}_\d{6}'
    matching_subdirs = '(mom\/\d{8}_\d{4}.mmclx)$'
    date_in_filename = '(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})_(?P<hour>\d{2})(?P<minute>\d{2})'
#  [MIRA.path.spec]
#    # mastering regex (here to exclude ppi and stuff)
#    base_dir = '/lacroshome/mira/data/NMRA/'
#    matching_subdirs = '(zspc_nc4\/\d{8}.*D\d{8}_T\d{4}.*standard.nc4)'
#    date_in_filename = 'D(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})_T(?P<hour>\d{2})(?P<minute>\d{2})'
  # this general settings need to be handed down to the params
  [MIRA.generic]
    time_variable = 'time'
    time_microsec_variable = 'microsec'
    range_variable = 'range'
    colormap = "gist_rainbow"
    which_path = 'mmclx'
    # define how the values from the nc file have to
    # be converted (strings defined in pyLARDA.helpers)
    time_conversion = 'unix'
    range_conversion = 'none'
    var_conversion = 'none'
    ncreader = 'timeheight'
    # if identifier is given read from ncfile, else define here
    identifier_rg_unit = 'units'
    identifier_var_unit = 'units'
    identifier_var_lims = 'yrange'
    #var_lims = [-40, 20]
  [MIRA.params.Zg]
    variable_name = 'Zg'
    #colormap = 'rainbow'
    #which_path = 'mmclx'
  [MIRA.params.sw]
    variable_name = 'RMSg'
  [MIRA.params.noiseco]
    variable_name = 'HSDco'
 [MIRA.params.noisecx]
    variable_name = 'HSDcx'
  [MIRA.params.VELg]
    variable_name = 'VELg'
    colormap = 'carbonne'
  [MIRA.params.LDRg]
    variable_name = 'LDRg'
    colormap = 'LDR'
#  [MIRA.params.Zspec]
#    which_path = 'spec'
#    variable_name = 'Z'
#    vel_variable = 'velocity'
#    ncreader = 'spec'
#    var_unit = 'Z m-1 s'
#    var_lims = [-50, 20]
#    rg_unit = 'm'
#    var_conversion = 'transposedim+invert3rd'
#    dimorder = [2,1,0] # (velocity, range, time as in the files from alexanders conversion)

#[peakTree]
#  [peakTree.path.nc4]
#    # mastering regex (here to exclude ppi and stuff)
#    base_dir = '/lacroshome/mira/data/NMRA/peakTree/'
#    matching_subdirs = '(\d{8}_\d{4}_Pun_peakTree.nc4)'
#    date_in_filename = '(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})_(?P<hour>\d{2})(?P<minute>\d{2})'
#  # this general settings need to be handed down to the params
#  [peakTree.generic]
#    time_variable = 'timestamp'
#    range_variable = 'range'
#    colormap = "gist_rainbow"
#    which_path = 'nc4'
#    # define how the values from the nc file have to
#    # be converted (strings defined in pyLARDA.helpers)
#    time_conversion = 'unix'
#    range_conversion = 'none'
#    var_conversion = 'none'
#    ncreader = 'timeheight'
#    # if identifier is given read from ncfile, else define here
#    identifier_rg_unit = 'units'
#    identifier_var_unit = 'units'
#    identifier_var_lims = 'yrange'
#    #var_lims = [-40, 20]
#  [peakTree.params.tree]
#    variable_name = 'tree'
#    ncreader = 'peakTree'
#    rg_unit = 'm'
#    var_lims = [-99, -99]
#    var_unit = ''



[CLOUDNET]
  [CLOUDNET.path.categorize]
    # mastering regex (here to exclude ppi and stuff)
    base_dir = '/lacroshome/cloudnet/data/polarstern/processed/categorize/'
    matching_subdirs = '(\d{4}\/\d{8}.*.nc)'
    date_in_filename = '(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})_'
  [CLOUDNET.path.productsiwc]
    # mastering regex (here to exclude ppi and stuff)
    base_dir = '/lacroshome/cloudnet/data/polarstern/products/iwc-Z-T-method/'
    matching_subdirs = '(\d{4}\/\d{8}.*.nc)'
    date_in_filename = '(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})_'
  [CLOUDNET.path.productsclass]
    # mastering regex (here to exclude ppi and stuff)
    base_dir = '/lacroshome/cloudnet/data/polarstern/products/classification/'
    matching_subdirs = '(\d{4}\/\d{8}.*.nc)'
    date_in_filename = '(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})_'
  [CLOUDNET.path.productslwcs]
    # mastering regex (here to exclude ppi and stuff)
    base_dir = '/lacroshome/cloudnet/data/polarstern/products/lwc-scaled-adiabatic/'
    matching_subdirs = '(\d{4}\/\d{8}.*.nc)'
    date_in_filename = '(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})_'
  [CLOUDNET.path.productslwc]
    # mastering regex (here to exclude ppi and stuff)
    base_dir = '/lacroshome/cloudnet/data/polarstern/products/lwc-adiabatic-method/'
    matching_subdirs = '(\d{4}\/\d{8}.*.nc)'
    date_in_filename = '(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})_'
  [CLOUDNET.generic]
    # this general settings need to be handed down to the params
    time_variable = 'time'
    range_variable = 'height'
    colormap = "gist_rainbow"
    time_conversion = 'beginofday'
    range_conversion = 'sealevel2range'
    var_conversion = 'none'
    ncreader = 'timeheight'
    # if identifier is given read from ncfile, else define here
    identifier_rg_unit = 'units'
    identifier_var_unit = 'units'
    identifier_var_lims = 'plot_range'
    identifier_fill_value = 'missing_value'
    identifier_history = 'history'
    #var_lims = [-40, 20]
  [CLOUDNET.params.Z]
    variable_name = 'Z'
    which_path = 'categorize'
    var_conversion = 'z2lin'
  [CLOUDNET.params.VEL]
    variable_name = 'v'
    which_path = 'categorize'
    var_conversion = 'none'
    colormap = 'carbonne'
    var_lims = [-3, 3]
  [CLOUDNET.params.WIDTH]
    variable_name = 'width'
    which_path = 'categorize'
  [CLOUDNET.params.LDR]
    variable_name = 'ldr'
    which_path = 'categorize'
    var_conversion = 'z2lin'
  [CLOUDNET.params.T]
    variable_name = 'temperature'
    which_path = 'categorize'
    range_variable = 'model_height'
  [CLOUDNET.params.q]
    variable_name = 'specific_humidity'
    which_path = 'categorize'
    range_variable = 'model_height'
  [CLOUDNET.params.P]
    variable_name = 'pressure'
    which_path = 'categorize'
    range_variable = 'model_height'
  [CLOUDNET.params.UWIND]
    variable_name = 'uwind'
    which_path = 'categorize'
    range_variable = 'model_height'
  [CLOUDNET.params.VWIND]
    variable_name = 'vwind'
    which_path = 'categorize'
    range_variable = 'model_height'
  [CLOUDNET.params.beta]
    variable_name = 'beta'
    which_path = 'categorize'
  [CLOUDNET.params.depol]
    variable_name = 'lidar_depolarisation'
    which_path = 'categorize'    
    var_unit = '%'
    var_lims = [0.0, 0.3]
  [CLOUDNET.params.IWC]
    variable_name = 'iwc'
    which_path = 'productsiwc'
  [CLOUDNET.params.CLASS]
    variable_name = 'target_classification'
    which_path = 'productsclass'
    var_unit = ""
    var_lims = [0, 10]
    colormap = 'cloudnet_target'
    fill_value = -99
  [CLOUDNET.params.LWP]
    variable_name = 'lwp'
    which_path = 'categorize'    
    ncreader = 'time'
  [CLOUDNET.params.LWC]
    variable_name = 'lwc_adiabatic'
    which_path = 'productslwc'    
  [CLOUDNET.params.LWC_S]
    variable_name = 'lwc'
    which_path = 'productslwcs'    

[POLLY]
  [POLLY.path.nc]
    # mastering regex (here to exclude ppi and stuff)
    base_dir = '/lacroshome/cloudnet/data/polarstern/calibrated/pollyxt/'
    matching_subdirs = '(\d{4}\/\d{8}.*.nc)'
    date_in_filename = '(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})_'
  # this general settings need to be handed down to the params
  [POLLY.generic]
    time_variable = 'time'
    range_variable = 'range'
    colormap = "gist_rainbow"
    which_path = 'nc'
    # define how the values from the nc file have to
    # be converted (strings defined in pyLARDA.helpers)
    time_conversion = 'beginofday'
    range_conversion = 'none'
    var_conversion = 'none'
    ncreader = 'timeheight'
    # if identifier is given read from ncfile, else define here
    identifier_rg_unit = 'units'
    identifier_var_unit = 'units'
    identifier_var_lims = 'plot_range'
    identifier_fill_value = 'missing_value'
  [POLLY.params.attbsc532]
    variable_name = 'att_beta_0532'
    var_unit = 'sr^-1 m^-1'
    var_lims = [3e-7, 1e-4]
  [POLLY.params.attbsc1064]
    variable_name = 'att_beta_1064'
    var_unit = 'sr^-1 m^-1'
    var_lims = [3e-7, 1e-4]
  [POLLY.params.depol]
    variable_name = 'volume_depolarization'
    var_unit = '%'
    var_lims = [0.0, 0.3]

#[CEILO]
#  [CEILO.path.nc]
#    # mastering regex (here to exclude ppi and stuff)
#    base_dir = '/lacroshome/cloudnet/data/punta-arenas/calibrated/chm15x/'
#    matching_subdirs = '(\d{4}\/\d{8}.*.nc)'
#    date_in_filename = '(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})_'
#  # this general settings need to be handed down to the params
#  [CEILO.generic]
#    time_variable = 'time'
#    range_variable = 'range'
#    colormap = "gist_rainbow"
#    which_path = 'nc'
#    # define how the values from the nc file have to
#    # be converted (strings defined in pyLARDA.helpers)
#    time_conversion = 'beginofday'
#    range_conversion = 'none'
#    var_conversion = 'none'
#    ncreader = 'timeheight'
#    # if identifier is given read from ncfile, else define here
#    identifier_rg_unit = 'units'
#    identifier_var_unit = 'units'
#    identifier_var_lims = 'plot_range'
#    identifier_fill_value = 'missing_value'
#  [CEILO.params.beta]
#    variable_name = 'beta'
#    var_unit = 'sr^-1^ m^-2'
#    var_lims = [0, 1e-2]
#    rg_unit = 'm'
#  [CEILO.params.cbh]
#    variable_name = 'att_beta_1064'
#    var_unit = 'm'
#    var_lims = [0, 1e-2]
#    rg_unit = 'm'

